package recipes.users;

import com.speedment.orm.config.model.Column;
import com.speedment.orm.config.model.Table;
import com.speedment.orm.core.manager.sql.SqlManager;
import com.speedment.orm.platform.Platform;
import com.speedment.orm.platform.component.ManagerComponent;
import com.speedment.orm.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import java.lang.Long;
import java.lang.String;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.users'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface UsersManager extends SqlManager<Long, Users, UsersBuilder> {
    
    @Override
    default Long primaryKeyFor(Users entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("recipes.recipes.users");
    }
    
    @Override
    default Class<UsersManager> getManagerClass() {
        return UsersManager.class;
    }
    
    @Override
    default Class<Users> getEntityClass() {
        return Users.class;
    }
    
    @Override
    default Class<UsersBuilder> getBuilderClass() {
        return UsersBuilder.class;
    }
    
    @Override
    default Object get(Users entity, Column column) {
        switch (column.getName()) {
            case "id" : return entity.getId();
            case "name" : return entity.getName();
            case "password" : return entity.getPassword();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    default void set(UsersBuilder entity, Column column, Object value) {
        switch (column.getName()) {
            case "id" : entity.setId((Long) value); break;
            case "name" : entity.setName((String) value); break;
            case "password" : entity.setPassword((String) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static UsersManager get() {
        return Platform.get().get(ManagerComponent.class).manager(UsersManager.class);
    }
}