package recipes.recipes;

import com.speedment.orm.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.recipes'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface RecipesBuilder extends Recipes, Buildable<Recipes> {
    
    RecipesBuilder setId(Long id);
    
    RecipesBuilder setName(String name);
    
    RecipesBuilder setText(String text);
}