package recipes.ratings;

import com.speedment.orm.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.ratings'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface RatingsBuilder extends Ratings, Buildable<Ratings> {
    
    RatingsBuilder setId(Long id);
    
    RatingsBuilder setUsersId(Long usersId);
    
    RatingsBuilder setRecipesId(Long recipesId);
    
    RatingsBuilder setRating(Integer rating);
}