package recipes.ratings;

import com.speedment.orm.config.model.Column;
import com.speedment.orm.config.model.Table;
import com.speedment.orm.core.manager.sql.SqlManager;
import com.speedment.orm.platform.Platform;
import com.speedment.orm.platform.component.ManagerComponent;
import com.speedment.orm.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Long;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.ratings'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface RatingsManager extends SqlManager<Long, Ratings, RatingsBuilder> {
    
    @Override
    default Long primaryKeyFor(Ratings entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("recipes.recipes.ratings");
    }
    
    @Override
    default Class<RatingsManager> getManagerClass() {
        return RatingsManager.class;
    }
    
    @Override
    default Class<Ratings> getEntityClass() {
        return Ratings.class;
    }
    
    @Override
    default Class<RatingsBuilder> getBuilderClass() {
        return RatingsBuilder.class;
    }
    
    @Override
    default Object get(Ratings entity, Column column) {
        switch (column.getName()) {
            case "id" : return entity.getId();
            case "users_id" : return entity.getUsersId();
            case "recipes_id" : return entity.getRecipesId();
            case "rating" : return entity.getRating();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    default void set(RatingsBuilder entity, Column column, Object value) {
        switch (column.getName()) {
            case "id" : entity.setId((Long) value); break;
            case "users_id" : entity.setUsersId((Long) value); break;
            case "recipes_id" : entity.setRecipesId((Long) value); break;
            case "rating" : entity.setRating((Integer) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static RatingsManager get() {
        return Platform.get().get(ManagerComponent.class).manager(RatingsManager.class);
    }
}