package recipes.ratings.impl;

import com.speedment.orm.core.manager.sql.AbstractSqlManager;
import java.lang.RuntimeException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;
import recipes.ratings.Ratings;
import recipes.ratings.RatingsBuilder;
import recipes.ratings.RatingsManager;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.ratings'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class RatingsManagerImpl extends AbstractSqlManager<Long, Ratings, RatingsBuilder> implements RatingsManager {
    
    public RatingsManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public RatingsBuilder builder() {
        return new RatingsImpl();
    }
    
    @Override
    public RatingsBuilder toBuilder(Ratings prototype) {
        return new RatingsImpl(prototype);
    }
    
    protected Ratings defaultReadEntity(ResultSet resultSet) {
        final RatingsBuilder builder = builder();
        try {
            builder.setId(resultSet.getLong("id"));
            builder.setUsersId(resultSet.getLong("users_id"));
            builder.setRecipesId(resultSet.getLong("recipes_id"));
            builder.setRating(resultSet.getInt("rating"));
        }
        catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        }
        return builder;
    }
}