package recipes.users.impl;

import com.speedment.orm.core.manager.sql.AbstractSqlManager;
import java.lang.RuntimeException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;
import recipes.users.Users;
import recipes.users.UsersBuilder;
import recipes.users.UsersManager;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.users'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class UsersManagerImpl extends AbstractSqlManager<Long, Users, UsersBuilder> implements UsersManager {
    
    public UsersManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public UsersBuilder builder() {
        return new UsersImpl();
    }
    
    @Override
    public UsersBuilder toBuilder(Users prototype) {
        return new UsersImpl(prototype);
    }
    
    protected Users defaultReadEntity(ResultSet resultSet) {
        final UsersBuilder builder = builder();
        try {
            builder.setId(resultSet.getLong("id"));
            builder.setName(resultSet.getString("name"));
            builder.setPassword(resultSet.getString("password"));
        }
        catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        }
        return builder;
    }
}