package recipes.users.impl;

import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;
import recipes.users.Users;
import recipes.users.UsersBuilder;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'project_1.recipes.recipes.users'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class UsersImpl implements UsersBuilder {
    
    private Long id;
    private String name;
    private String password;
    
    public UsersImpl() {
        
    }
    
    public UsersImpl(final Users users) {
        setId(users.getId());
        setName(users.getName());
        setPassword(users.getPassword());
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    @Override
    public UsersImpl setId(Long id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getName() {
        return name;
    }
    
    @Override
    public UsersImpl setName(String name) {
        this.name = name;
        return this;
    }
    
    @Override
    public String getPassword() {
        return password;
    }
    
    @Override
    public UsersImpl setPassword(String password) {
        this.password = password;
        return this;
    }
    
    @Override
    public Users build() {
        return new UsersImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("name = "+Objects.toString(getName()));
        sj.add("password = "+Objects.toString(getPassword()));
        return "UsersImpl "+sj.toString();
    }
}