package recipes;

import com.speedment.orm.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'project_1'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class Project1Application extends SpeedmentApplicationLifecycle<Project1Application> {
    
    public Project1Application() {
        setSpeedmentApplicationMetadata(new Project1ApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        loadAndSetProject();
        put(new recipes.ratings.impl.RatingsManagerImpl());
        put(new recipes.recipes.impl.RecipesManagerImpl());
        put(new recipes.users.impl.UsersManagerImpl());
        super.onInit();
    }
}